export const ADD_ENTRY = 'ADD_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const UPDATE_ENTRY_TYPE = 'UPDATE_ENTRY_TYPE';
export const UPDATE_ENTRY_DESCRIPTION = 'UPDATE_ENTRY_DESCRIPTION';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const UPDATE_COUNTER = 'UPDATE_COUNTER';
